ktor:
    development: false
    application:
        modules:
            - io.ktor.chat.LoggingKt.logging
            - io.ktor.chat.SecurityKt.security
            - io.ktor.chat.MailKt.mail
            - io.ktor.chat.SerializationKt.contentNegotiation
            - io.ktor.chat.RestKt.rest
            - io.ktor.chat.HealthCheckKt.healthCheck
            - io.ktor.chat.DatabasesKt.database
            - io.ktor.chat.RepositoriesKt.repositories
            - io.ktor.chat.AuthenticationKt.auth
            - io.ktor.chat.UsersKt.users
            - io.ktor.chat.MessagesKt.messages
            - io.ktor.chat.RoomsKt.rooms
            - io.ktor.chat.MembershipsKt.members
            - io.ktor.chat.SignalingKt.signaling
            - io.ktor.chat.DocsKt.docs
    deployment:
        port: ${?PORT:9090}

jwt:
    audience: audience
    issuer: issuer
    realm: realm

security:
    secret: S3crE4_P@55w0Rd

database:
    main:
        #r2dbc:postgresql://dpg-d76ekb4r85hc73bj32bg-a.singapore-postgres.render.com/db_ktor_chat?sslMode=require&connectTimeout=1000
        #url: "r2dbc:postgresql://dpg-d76ekb4r85hc73bj32bg-a:5432/db_ktor_chat?connectTimeout=1000"
        #url: "r2dbc:postgresql://dpg-d76ekb4r85hc73bj32bg-a.singapore-postgres.render.com/db_ktor_chat?sslMode=require&connectTimeout=1000"
        #postgresql://postgres:vKMveVhKoFKDcyicBmzqhvBNIREeggNa@junction.proxy.rlwy.net:22384/railway
        host: "junction.proxy.rlwy.net"
        database: "railway"
        port: 22384
        secure: "false"
        user: "postgres"
        driver: "postgresql"
        password: "vKMveVhKoFKDcyicBmzqhvBNIREeggNa"
    test:
        host: "r2dbc:h2:file:///../h2/db"
        database: "db"
        port: 5432
        secure: "false"
        user: "root"
        driver: "org.h2.Driver"
        password: ""

